name: Generate Changelog

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  update_changelog:
    name: Update Changelog
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install github_changelog_generator
        run: gem install github_changelog_generator

      - name: Generate Changelog
        run: |
          github_changelog_generator -u ${{ github.repository_owner }} -p $(basename ${{ github.repository }}) --token ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "chore: update changelog" || echo "No changes to commit"
          git push