name: Update Changelog

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  update_changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Release Notes
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Append commits to CHANGELOG.md
        run: |
          echo "## Commits in this version" >> CHANGELOG.md
          git log --pretty=format:"- %h %s" --no-merges -n 20 >> CHANGELOG.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "chore: update changelog" || echo "No changes to commit"
          git push
